export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const GET_SINGLE_FOOD = "GET_SINGLE_FOOD";
export const GET_SINGLE_FOOD_SUCCESS = "GET_SINGLE_FOOD_SUCCESS";
export const GET_ALL_FOOD = "GET_ALL_FOOD";
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS";
export const CREATE_FOOD = "CREATE_FOOD";
export const CREATE_FOOD_SUCCESS = "CREATE_FOOD_SUCCESS";
export const UPDATE_FOOD = "UPDATE_FOOD";
export const UPDATE_FOOD_SUCCESS = "UPDATE_FOOD_SUCCESS";
export const DELETE_FOOD = "DELETE_FOOD";
export const DELETE_FOOD_SUCCESS = "DELETE_FOOD_SUCCESS";
export const SELECT_FOOD = "SELECT_FOOD";

export const GET_SINGLE_CATEGORY = "GET_SINGLE_CATEGORY";
export const GET_SINGLE_CATEGORY_SUCCESS = "GET_SINGLE_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const ADD_LOG = "ADD_LOG";

export const UPDATE_SETTING = "UPDATE_SETTING";
